### ISSUE TITLE
GeoTrellis Documentation Overhaul

### ISSUE THREAD

**Issue by CloudNiner** [locationtech/geotrellis#3304]
This Epic encapsulates the GeoTrellis team effort to overhaul the documentation site replacing RTD with mdoc + docusaurus so that we have CI compiled docs that are built and run on each GeoTrellis commit to master. This work will build on newer docs developed in https://github.com/geotrellis/geotrellis-workshop and https://github.com/geotrellis/geotrellis-docs and is intended to address our goals of updating our out of date documentation and increasing maintainability.

### Tasks (Break into Issues)

- [ ] Integrate mdoc / docusaurus build into locationtech/geotrellis + CI
- [ ] Migrate existing pages from geotrellis/geotrellis-docs
- [ ] Motiviation and Installation pages
- [ ] Getting Started page
- [ ] Rasters and Raster operations
- [ ] RasterSources
- [ ] MapAlgebra
- [ ] Vector operations (load/unload GeoJSON)
- [ ] GDAL
- [ ] Spark

**Comment by CloudNiner** [comment]
As much as possible, we should align our documentation pages to align with the four quadrants presented in https://documentation.divio.com/

These are:
- Tutorials
- How To
- Reference
- Explanation

I've updated the existing open issues to reflect this as much as possible by aligning on terminology and splitting subtasks in the issue by the quadrant they align with.
